### ISSUE TITLE
fix Update table, contains ID_Tables

### ISSUE THREAD

**Issue by KIET1996** [KIET1996/QLNH#44]
Table Controller -> hàm UpdateTable -> Query chứa ID_Table ->Nên xóa đi

**Comment by huavoanhthu** [comment]
Tại sao phải xóa ID_Table vậy Kiệt nếu xóa nó bị lỗi nó đâu biết sửa id nào

**Comment by KIET1996** [comment]
id table chỉ sử dụng ở where khi cập nhật nhưng  trong câu truy vấn có set id table cập nhật
trong sql t sửa r
